// autogenerated: do NOT edit manually

namespace Platinum.VisualStudio.Tests
{
    /// <summary />
    public static class ER
    {
        /// <summary>
        /// Smoke test
        /// Actor: Platypus, Code: 1001
        /// </summary>
        public const string Smoke = "Smoke";
    }


    /// <summary />
    public static class EV
    {
    }
}

/* eof */
