// autogenerated: do NOT edit manually
using Platinum.Configuration;
using System;
using System.Configuration;

namespace Platinum.Globalization
{
    public partial class CultureFactoryConfiguration : ConfigurationSection
    {
        public static CultureFactoryConfiguration Current
        {
            get { return AppConfiguration.SectionGet<CultureFactoryConfiguration>( "platinum/cultureFactory" ); }
        }


        [ConfigurationProperty( "cultures", IsDefaultCollection = false )]
        [ConfigurationCollection( typeof( CultureOverrideDefinition ), AddItemName = "add" )]
        public ConfigurationElementCollection<CultureOverrideDefinition> Cultures
        {
            get { return (ConfigurationElementCollection<CultureOverrideDefinition>) base[ "cultures" ]; }
        }
    }


    public partial class CultureOverrideDefinition : ConfigurationElement
    {
        [ConfigurationProperty( "culture", IsKey = true, IsRequired = true )]
        public string Culture
        {
            get { return (string) this[ "culture" ]; }
            set { this[ "culture" ] = value; }
        }

        [ConfigurationProperty( "dateTimeFormat", IsRequired = true )]
        public DateTimeFormatDefinition DateTimeFormat
        {
            get { return (DateTimeFormatDefinition) this[ "dateTimeFormat" ]; }
            set { this[ "dateTimeFormat" ] = value; }
        }

        [ConfigurationProperty( "numberFormat", IsRequired = true )]
        public NumberFormatDefinition NumberFormat
        {
            get { return (NumberFormatDefinition) this[ "numberFormat" ]; }
            set { this[ "numberFormat" ] = value; }
        }
    }

    public partial class DateTimeFormatDefinition : ConfigurationElement
    {
        [ConfigurationProperty( "shortDatePattern" )]
        public string ShortDatePattern
        {
            get { return (string) this[ "shortDatePattern" ]; }
            set { this[ "shortDatePattern" ] = value; }
        }

        [ConfigurationProperty( "dateSeparator" )]
        public string DateSeparator
        {
            get { return (string) this[ "dateSeparator" ]; }
            set { this[ "dateSeparator" ] = value; }
        }

        [ConfigurationProperty( "timeSeparator" )]
        public string TimeSeparator
        {
            get { return (string) this[ "timeSeparator" ]; }
            set { this[ "timeSeparator" ] = value; }
        }

        [ConfigurationProperty( "firstDayOfWeek" )]
        public DayOfWeek? FirstDayOfWeek
        {
            get { return (DayOfWeek?) this[ "firstDayOfWeek" ]; }
            set { this[ "firstDayOfWeek" ] = value; }
        }
    }

    public partial class NumberFormatDefinition : ConfigurationElement
    {
        [ConfigurationProperty( "numberDecimalSeparator" )]
        public string NumberDecimalSeparator
        {
            get { return (string) this[ "numberDecimalSeparator" ]; }
            set { this[ "numberDecimalSeparator" ] = value; }
        }

        [ConfigurationProperty( "currencyGroupSeparator" )]
        public string CurrencyGroupSeparator
        {
            get { return (string) this[ "currencyGroupSeparator" ]; }
            set { this[ "currencyGroupSeparator" ] = value; }
        }
    }
}

/* eof */
