// autogenerated: do NOT edit manually
using Platinum.Configuration;
using System;
using System.Configuration;

namespace Platinum.Resolver
{
    public partial class ResolverConfiguration : ConfigurationSection
    {
        public static ResolverConfiguration Current
        {
            get { return AppConfiguration.SectionGet<ResolverConfiguration>( "platinum/resolver" ); }
        }


        [ConfigurationProperty( "customResolvers", IsDefaultCollection = false )]
        [ConfigurationCollection( typeof( ResolverDefinition ), AddItemName = "add" )]
        public ConfigurationElementCollection<ResolverDefinition> CustomResolvers
        {
            get { return (ConfigurationElementCollection<ResolverDefinition>) base[ "customResolvers" ]; }
        }
    }


    public partial class ResolverDefinition : ConfigurationElement
    {
        [ConfigurationProperty( "scheme", IsKey = true, IsRequired = true )]
        public string Scheme
        {
            get { return (string) this[ "scheme" ]; }
            set { this[ "scheme" ] = value; }
        }

        [ConfigurationProperty( "moniker", IsRequired = true )]
        public string Moniker
        {
            get { return (string) this[ "moniker" ]; }
            set { this[ "moniker" ] = value; }
        }
    }
}

/* eof */
