// autogenerated: do NOT edit manually
using Platinum.Data;

namespace Platinum.Data.Tests
{
    /// <summary />
    internal static partial class Statements
    {
        /// <summary />
        internal static partial class Sql
        {
            /// <summary />
            internal static string DbError
            { get { return Db.Command( "Sql/DbError" ); } }

            /// <summary />
            internal static string DbErrorArg
            { get { return Db.Command( "Sql/DbErrorArg" ); } }

            /// <summary />
            internal static string Multi1
            { get { return Db.Command( "Sql/Multi1" ); } }

            /// <summary />
            internal static string Multi2
            { get { return Db.Command( "Sql/Multi2" ); } }

            /// <summary />
            internal static string Query
            { get { return Db.Command( "Sql/Query" ); } }

            /// <summary />
            internal static string Single
            { get { return Db.Command( "Sql/Single" ); } }
        }
    }
}